config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dashboard#index"

  get 'dashboard/search_giphy' => 'dashboard#search_giphy', as: :search_giphy

  resources :gifs, only: [:index, :create, :show]
  resources :users, only: [:show]

  delete 'gifs/remove' => 'gifs#remove', as: :remove
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable

  validates :giphy_id, uniqueness: { scope: :user_id, message: "Already exists" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gifs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  GIFS_PER_PAGE = 10

  rescue_from Exception do |exception|
    status = :internal_server_error # 500

    status = :not_found if exception.kind_of? ActiveRecord::RecordNotFound # 404
    status = :bad_request if exception.kind_of? ActiveRecord::RecordInvalid # 400

    if exception.kind_of? PG::NotNullViolation
      status = :bad_request
      message = 'Database field should NOT be NULL'
    end

    unless message.present?
      message = exception.message
    end

    render_response([message], status)
  end

  private

  def build_success_response(response_data)
    { success: true, data: response_data }
  end

  def build_error_repsonse(response_data)
    { success: false, errors: [response_data] }
  end

  def render_response(request_response, status = :ok)
    response = (status == :ok || status == :created) ? build_success_response(request_response) : build_error_repsonse(request_response)

    render :json => response, :status => status
  end
end

app/controllers/dashboard_controller.rb
require 'will_paginate/array'

class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def search_giphy
    if params['q'].present?
      page = (params[:page] || 1).to_i

      get_gifs_response = Giphy::ApiClient.get_gifs({
        :q => params['q'],
        :limit => GIFS_PER_PAGE,
        :offset => page-1
      })

      total_count = get_gifs_response['pagination']['total_count']

      pagination_options = {
        :page => page,
        :per_page => GIFS_PER_PAGE,
        :total_entries => total_count
      }

      @gifs = get_gifs_response['data']
      @pages = (1..total_count).to_a.paginate(pagination_options)

      if user_signed_in?
        @gifs.each{|x| x['exists'] = current_user.gifs.map(&:giphy_id).include?(x['id'])}
      end
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_filter :authenticate_user!

  def create
    if params['gifs'].present?
      gifs_details = Giphy::ApiClient.get_gifs_by_id({
        :ids => params['gifs'].map{ |k,v| v['giphy_id'] }
      })

      gifs_by_id = {}
      gifs_details.each{ |x| gifs_by_id[x['id']] = x }

      params['gifs'].each do |k, v|
        gif = Gif.new
        gif.user_id = current_user.id
        gif.giphy_id = v['giphy_id']
        gif.tag_list = v['tags']

        gif.slug = gifs_by_id[v['giphy_id']]['slug']
        gif.image = gifs_by_id[v['giphy_id']]['image']
        gif.url = gifs_by_id[v['giphy_id']]['url']
        gif.source = gifs_by_id[v['giphy_id']]['source']
        gif.import_datetime = gifs_by_id[v['giphy_id']]['import_datetime']

        gif.save!
      end

      data = current_user.gifs
      render_response(data, :created)
    else
      render_response('Please select some gifs for your collection', :bad_request)
    end
  end

  def index
    page = (params[:page] || 1).to_i
    @gifs = current_user.gifs
              .paginate(:page => page, :per_page => GIFS_PER_PAGE)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def remove
    if params['gifs'].present?
      deleted_gifs = current_user.gifs.where(:giphy_id => params['gifs']).destroy_all
      render_response(deleted_gifs, :ok)
    else
      render_response('There is nothing to remove', :bad_request)
    end
  end

  def show
    @gif = current_user.gifs.where(:giphy_id => params[:id]).last
  end

  private
    def permitted_params
      params.permit(:user_id, :giphy_id, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_action_button(gif)
    if gif['exists']
      view_gif_button(gif['id'])
    else
      button_tag 'Add', type: 'button', :class => 'add-gif btn btn-primary'
    end
  end

  def show_tags_input(exists)
    unless exists
      text_field_tag "tags", '', :class => 'tags', :disabled => exists
    end
  end

  def show_checkbox(exists)
    unless exists
      check_box_tag('select', value = '1', checked = false, options = {:class => 'select_gif'})
    end
  end

  def show_select_all
    check_box_tag('select_all', value = '1', checked = false, options = {})
  end

  def show_pagination(pages)
    content_tag(:div, will_paginate(pages), class: 'row')
  end

  def global_message(key, value)
    content_tag(:div, value, :class => "alert alert-#{key}", role: "alert")
  end

  def show_tag_list(tag_list)
    tag_list.join(', ') if tag_list.present?
  end

  def view_gif_button(id)
    link_to 'View', gif_path(id), role: 'button', :class => 'view-gif btn btn-info'
  end

  def remove_gif_button
    button_tag 'Remove', type: 'button', :class => 'remove-gif btn btn-danger'
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    flash.now[:error] = resource.errors.full_messages.first
    return ''
  end
end

app/views/dashboard/_list.html.erb
<% if @gifs.present? %>
  <div class='pull-left'>
    <%= button_tag 'Select all', type: 'button', :class => 'select-all-gifs btn btn-info' %>
  </div>
  <div class='pull-right'>
    <%= button_tag 'Add all to my collection', :class => 'add-selected-gifs btn btn-primary' %>
  </div>
  <div class="page-header"></div>
  <div class='pull-right'><%= show_pagination(@pages) %></div>
  <div class='row'>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th class='show-centered'></th>
          <th class='show-centered'>Gif</th>
          <th class='show-centered'>Tags</th>
          <th class='show-centered'>Actions</th>
        </tr>
      </thead>
      <% @gifs.each_with_index do |gif, index| %>
        <tr>
          <td class="checkbox show-centered">
            <label><%= show_checkbox(gif['exists']) %></label>
          </td>
          <td class='show-centered'><%= image_tag gif['image'] %></td>
          <td class='show-centered'><%= show_tags_input(gif['exists']) %></td>
          <td class='show-centered'>
            <%= show_action_button(gif) %>
            <%= hidden_field_tag 'giphy_id',  gif['id'] %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class='pull-right'><%= show_pagination(@pages) %></div>
<% else %>
  <div><h2>There is nothing matching your search!</h2></div>
<% end %>

app/views/dashboard/index.html.erb
<%= form_tag search_giphy_path, :method => :get, :class => 'navbar-form navbar-left', :role => 'search', :remote => true, :id => 'search_form' %>
	<div> <h1>You can search for your favorite gifs using the Giphy API</h1></div>
  <div class="row">
    <div class="input-group">
      <input type="text" name='q' class="form-control" placeholder="Search&hellip;">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary">Go</button>
      </span>
    </div>
  </div>
  <div class="page-header">
  </div>
  <div class="row" id="gifs">
  </div>

app/views/dashboard/search_giphy.js.erb
$("#gifs").html("<%= escape_javascript(render partial: 'list', locals: { gifs: @gifs } ) %>");

app/views/gifs/_list.html.erb
<% if @gifs.present? %>
  <div class='pull-right'><%= show_pagination(@gifs) %></div>
  <div id="gifs">
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th class='show-centered'>Url</th>
          <th class='show-centered'>Image</th>
          <th class='show-centered'>Tags</th>
          <th class='show-centered' >Actions</th>
        </tr>
      </thead>
      <% @gifs.each_with_index do |gif, index| %>
        <tr>
          <td class='show-centered '><%= gif.giphy_id %></td>
          <td class='show-centered'><%= image_tag gif['image'] %></td>
          <td class='show-centered'><%= show_tag_list(gif.tag_list) %></td>
          <td class='show-centered'>
            <%= view_gif_button(gif.giphy_id) %>
            <%= remove_gif_button %>
            <%= hidden_field_tag 'giphy_id',  gif.giphy_id %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class='pull-right'><%= show_pagination(@gifs) %></div>
<% else %>
  <div> <h2>You don't have any gifs in your collection</div>
<% end %>

app/views/gifs/index.html.erb
<%= render partial: 'list', locals: { gifs: @gifs } %>

app/views/gifs/index.js.erb
$("#gifs").html("<%= escape_javascript(render partial: 'list', locals: { gifs: @gifs } ) %>");

app/views/gifs/show.html.erb
<%- if @gif.present? %>
  <div class="panel">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3 col-lg-3 " align="center">
          <%= image_tag @gif.image, class: "img-circle img-responsive" %>
        </div>
        <div class=" col-md-9 col-lg-9 ">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td>ID:</td>
                <td><%= @gif.giphy_id %></td>
              </tr>
              <tr>
                <td>Slug:</td>
                <td><%= @gif.slug %></td>
              </tr>
              <tr>
                <td>Url</td>
                <td><%= @gif.url %></td>
              </tr>
              <tr>
                <td>Source</td>
                <td><%= @gif.source %></td>
              </tr>
                <tr>
                <td>Import Date & Time</td>
                <td><%= @gif.import_datetime %></td>
              </tr>
              <tr>
                <td>Tags</td>
                <td><%= show_tag_list(@gif.tag_list) %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% else %>
<div><h2>Nothing to show</h2></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= render :partial => "shared/header" %>
    <div class='content'>
      <div id="flash">
        <%- flash.each do |key, value| %>
          <%= global_message(key, value) %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render :partial => "shared/footer" %>
  </div>
</body>
</html>

app/views/shared/_header.html.erb
<%- if user_signed_in? %>
  <nav role="navigation" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <li>
          <%= link_to 'My Giphy Collection', gifs_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%- if user_signed_in? %>
          <li>
            <p class="navbar-text">Signed in as <%= current_user.email %></p>
          </li>
          <li>
            <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
<% end %>